[2024-07-25T14:28:09.718-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:28:09.723-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [queued]>
[2024-07-25T14:28:09.727-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [queued]>
[2024-07-25T14:28:09.727-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:28:09.741-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 13:10:00+00:00
[2024-07-25T14:28:09.744-0300] {standard_task_runner.py:64} INFO - Started process 2590946 to run task
[2024-07-25T14:28:09.746-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T13:10:00+00:00', '--job-id', '2110', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpvythc9z0']
[2024-07-25T14:28:09.746-0300] {standard_task_runner.py:91} INFO - Job 2110: Subtask get_5m_info
[2024-07-25T14:28:09.774-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:28:09.822-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T13:10:00+00:00'
[2024-07-25T14:28:09.823-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:28:09.831-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:28:09.831-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:28:09.835-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T13:10:00+00:00, execution_date=20240725T131000, start_date=20240725T172809, end_date=20240725T172809
[2024-07-25T14:28:09.854-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2110 for task get_5m_info (too many values to unpack (expected 2); 2590946)
[2024-07-25T14:28:09.880-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:28:09.886-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:28:09.887-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:19.774-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:19.782-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [queued]>
[2024-07-25T14:30:19.786-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [queued]>
[2024-07-25T14:30:19.787-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:19.803-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 13:10:00+00:00
[2024-07-25T14:30:19.805-0300] {standard_task_runner.py:64} INFO - Started process 2593178 to run task
[2024-07-25T14:30:19.808-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T13:10:00+00:00', '--job-id', '2096', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp6kzenafl']
[2024-07-25T14:30:19.809-0300] {standard_task_runner.py:91} INFO - Job 2096: Subtask get_5m_info
[2024-07-25T14:30:19.838-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:19.880-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T13:10:00+00:00'
[2024-07-25T14:30:19.881-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:19.888-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:19.888-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:19.892-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T13:10:00+00:00, execution_date=20240725T131000, start_date=20240725T173019, end_date=20240725T173019
[2024-07-25T14:30:19.903-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2096 for task get_5m_info (too many values to unpack (expected 2); 2593178)
[2024-07-25T14:30:19.941-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:19.948-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:19.948-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:00:27.501-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:00:27.506-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [queued]>
[2024-07-25T15:00:27.510-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [queued]>
[2024-07-25T15:00:27.510-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:00:27.524-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 13:10:00+00:00
[2024-07-25T15:00:27.526-0300] {standard_task_runner.py:64} INFO - Started process 2619896 to run task
[2024-07-25T15:00:27.528-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T13:10:00+00:00', '--job-id', '2470', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp0vsyimwf']
[2024-07-25T15:00:27.529-0300] {standard_task_runner.py:91} INFO - Job 2470: Subtask get_5m_info
[2024-07-25T15:00:27.563-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:10:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:00:27.630-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T13:10:00+00:00'
[2024-07-25T15:00:27.631-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:00:27.712-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:00:27.713-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721924100&from=1721923800
[2024-07-25T15:00:27.993-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:00:27.994-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:00:27.997-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T13:10:00+00:00, execution_date=20240725T131000, start_date=20240725T180027, end_date=20240725T180027
[2024-07-25T15:00:28.029-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:00:28.035-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:00:28.036-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
