[2024-07-24T23:38:22.153-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T23:38:22.160-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T00:49:00+00:00 [queued]>
[2024-07-24T23:38:22.164-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T00:49:00+00:00 [queued]>
[2024-07-24T23:38:22.164-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T23:38:22.181-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_1m_info> on 2024-07-25 00:49:00+00:00
[2024-07-24T23:38:22.184-0300] {standard_task_runner.py:64} INFO - Started process 2274405 to run task
[2024-07-24T23:38:22.186-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_1m', 'get_1m_info', 'scheduled__2024-07-25T00:49:00+00:00', '--job-id', '1638', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpr6ipyy8w']
[2024-07-24T23:38:22.187-0300] {standard_task_runner.py:91} INFO - Job 1638: Subtask get_1m_info
[2024-07-24T23:38:22.218-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T00:49:00+00:00 [running]> on host Galaxybook.
[2024-07-24T23:38:22.273-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_1m' AIRFLOW_CTX_TASK_ID='get_1m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T00:49:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T00:49:00+00:00'
[2024-07-24T23:38:22.274-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T23:38:22.281-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T23:38:22.281-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 20, in get_info
    with open('../Datalake/mercado/mercado_1m.csv', 'a', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../Datalake/mercado/mercado_1m.csv'
[2024-07-24T23:38:22.287-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_1m, task_id=get_1m_info, run_id=scheduled__2024-07-25T00:49:00+00:00, execution_date=20240725T004900, start_date=20240725T023822, end_date=20240725T023822
[2024-07-24T23:38:22.300-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 1638 for task get_1m_info ([Errno 2] No such file or directory: '../Datalake/mercado/mercado_1m.csv'; 2274405)
[2024-07-24T23:38:22.318-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T23:38:22.330-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T23:38:22.331-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
