[2024-07-25T14:27:42.130-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:27:42.137-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [queued]>
[2024-07-25T14:27:42.141-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [queued]>
[2024-07-25T14:27:42.141-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:27:42.157-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:30:00+00:00
[2024-07-25T14:27:42.159-0300] {standard_task_runner.py:64} INFO - Started process 2590455 to run task
[2024-07-25T14:27:42.161-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:30:00+00:00', '--job-id', '2094', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpo_h9ay6n']
[2024-07-25T14:27:42.162-0300] {standard_task_runner.py:91} INFO - Job 2094: Subtask get_5m_info
[2024-07-25T14:27:42.195-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:27:42.240-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:30:00+00:00'
[2024-07-25T14:27:42.241-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:27:42.248-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:27:42.248-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:27:42.252-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:30:00+00:00, execution_date=20240725T123000, start_date=20240725T172742, end_date=20240725T172742
[2024-07-25T14:27:42.264-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2094 for task get_5m_info (too many values to unpack (expected 2); 2590455)
[2024-07-25T14:27:42.294-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:27:42.303-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:27:42.303-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:07.664-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:07.671-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [queued]>
[2024-07-25T14:30:07.674-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [queued]>
[2024-07-25T14:30:07.674-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:07.692-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:30:00+00:00
[2024-07-25T14:30:07.694-0300] {standard_task_runner.py:64} INFO - Started process 2592978 to run task
[2024-07-25T14:30:07.697-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:30:00+00:00', '--job-id', '2088', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmps9_rzv3e']
[2024-07-25T14:30:07.698-0300] {standard_task_runner.py:91} INFO - Job 2088: Subtask get_5m_info
[2024-07-25T14:30:07.731-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:07.784-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:30:00+00:00'
[2024-07-25T14:30:07.785-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:07.793-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:07.793-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:07.798-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:30:00+00:00, execution_date=20240725T123000, start_date=20240725T173007, end_date=20240725T173007
[2024-07-25T14:30:07.808-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2088 for task get_5m_info (too many values to unpack (expected 2); 2592978)
[2024-07-25T14:30:07.830-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:07.837-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:07.837-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:00:08.424-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:00:08.430-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [queued]>
[2024-07-25T15:00:08.434-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [queued]>
[2024-07-25T15:00:08.434-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:00:08.448-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:30:00+00:00
[2024-07-25T15:00:08.450-0300] {standard_task_runner.py:64} INFO - Started process 2619567 to run task
[2024-07-25T15:00:08.452-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:30:00+00:00', '--job-id', '2462', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp4dhfhd4f']
[2024-07-25T15:00:08.453-0300] {standard_task_runner.py:91} INFO - Job 2462: Subtask get_5m_info
[2024-07-25T15:00:08.481-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:30:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:00:08.539-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:30:00+00:00'
[2024-07-25T15:00:08.539-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:00:08.609-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:00:08.609-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721921700&from=1721921400
[2024-07-25T15:00:08.896-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:00:08.897-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:00:08.899-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:30:00+00:00, execution_date=20240725T123000, start_date=20240725T180008, end_date=20240725T180008
[2024-07-25T15:00:08.952-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:00:08.960-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:00:08.960-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
