[2024-07-25T14:27:29.852-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:27:29.861-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:27:29.865-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:27:29.865-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:27:29.882-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:10:00+00:00
[2024-07-25T14:27:29.885-0300] {standard_task_runner.py:64} INFO - Started process 2590267 to run task
[2024-07-25T14:27:29.887-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:10:00+00:00', '--job-id', '2087', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpmnhlsbzf']
[2024-07-25T14:27:29.888-0300] {standard_task_runner.py:91} INFO - Job 2087: Subtask get_5m_info
[2024-07-25T14:27:29.918-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:27:29.974-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:10:00+00:00'
[2024-07-25T14:27:29.974-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:27:29.984-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:27:29.985-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:27:29.989-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:10:00+00:00, execution_date=20240725T121000, start_date=20240725T172729, end_date=20240725T172729
[2024-07-25T14:27:30.000-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2087 for task get_5m_info (too many values to unpack (expected 2); 2590267)
[2024-07-25T14:27:30.021-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:27:30.027-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:27:30.028-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:00.337-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:00.343-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:30:00.346-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:30:00.346-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:00.363-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:10:00+00:00
[2024-07-25T14:30:00.365-0300] {standard_task_runner.py:64} INFO - Started process 2592820 to run task
[2024-07-25T14:30:00.368-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:10:00+00:00', '--job-id', '2084', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpqgh5z7qt']
[2024-07-25T14:30:00.369-0300] {standard_task_runner.py:91} INFO - Job 2084: Subtask get_5m_info
[2024-07-25T14:30:00.401-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:00.449-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:10:00+00:00'
[2024-07-25T14:30:00.449-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:00.455-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:00.456-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:00.459-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:10:00+00:00, execution_date=20240725T121000, start_date=20240725T173000, end_date=20240725T173000
[2024-07-25T14:30:00.472-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2084 for task get_5m_info (too many values to unpack (expected 2); 2592820)
[2024-07-25T14:30:00.500-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:00.547-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:00.547-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:49:23.528-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:49:23.535-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:49:23.538-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:49:23.538-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:49:23.554-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:10:00+00:00
[2024-07-25T14:49:23.556-0300] {standard_task_runner.py:64} INFO - Started process 2608801 to run task
[2024-07-25T14:49:23.558-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:10:00+00:00', '--job-id', '2158', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpqd18wxf0']
[2024-07-25T14:49:23.559-0300] {standard_task_runner.py:91} INFO - Job 2158: Subtask get_5m_info
[2024-07-25T14:49:23.591-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:49:23.645-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:10:00+00:00'
[2024-07-25T14:49:23.646-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:49:23.723-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T14:49:23.723-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721920500&from=1721920200
[2024-07-25T14:49:24.030-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T14:49:24.031-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:49:24.035-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:10:00+00:00, execution_date=20240725T121000, start_date=20240725T174923, end_date=20240725T174924
[2024-07-25T14:49:24.059-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T14:49:24.065-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:49:24.065-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:59:55.985-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:59:55.994-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:59:55.998-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [queued]>
[2024-07-25T14:59:55.998-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:59:56.011-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:10:00+00:00
[2024-07-25T14:59:56.012-0300] {standard_task_runner.py:64} INFO - Started process 2619358 to run task
[2024-07-25T14:59:56.015-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:10:00+00:00', '--job-id', '2457', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpngnnl4jg']
[2024-07-25T14:59:56.016-0300] {standard_task_runner.py:91} INFO - Job 2457: Subtask get_5m_info
[2024-07-25T14:59:56.046-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:10:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:59:56.104-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:10:00+00:00'
[2024-07-25T14:59:56.104-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:59:56.178-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T14:59:56.178-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721920500&from=1721920200
[2024-07-25T14:59:56.539-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T14:59:56.540-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:59:56.542-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:10:00+00:00, execution_date=20240725T121000, start_date=20240725T175955, end_date=20240725T175956
[2024-07-25T14:59:56.593-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T14:59:56.602-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:59:56.602-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
