[2024-07-25T14:27:47.153-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:27:47.159-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [queued]>
[2024-07-25T14:27:47.162-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [queued]>
[2024-07-25T14:27:47.163-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:27:47.176-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:35:00+00:00
[2024-07-25T14:27:47.178-0300] {standard_task_runner.py:64} INFO - Started process 2590545 to run task
[2024-07-25T14:27:47.179-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:35:00+00:00', '--job-id', '2097', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpof2vczox']
[2024-07-25T14:27:47.180-0300] {standard_task_runner.py:91} INFO - Job 2097: Subtask get_5m_info
[2024-07-25T14:27:47.206-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:27:47.253-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:35:00+00:00'
[2024-07-25T14:27:47.254-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:27:47.261-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:27:47.261-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:27:47.265-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:35:00+00:00, execution_date=20240725T123500, start_date=20240725T172747, end_date=20240725T172747
[2024-07-25T14:27:47.275-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2097 for task get_5m_info (too many values to unpack (expected 2); 2590545)
[2024-07-25T14:27:47.312-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:27:47.319-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:27:47.320-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:08.938-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:08.944-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [queued]>
[2024-07-25T14:30:08.948-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [queued]>
[2024-07-25T14:30:08.948-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:08.961-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:35:00+00:00
[2024-07-25T14:30:08.963-0300] {standard_task_runner.py:64} INFO - Started process 2592981 to run task
[2024-07-25T14:30:08.964-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:35:00+00:00', '--job-id', '2089', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmplti5kcht']
[2024-07-25T14:30:08.965-0300] {standard_task_runner.py:91} INFO - Job 2089: Subtask get_5m_info
[2024-07-25T14:30:08.990-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:09.036-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:35:00+00:00'
[2024-07-25T14:30:09.037-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:09.043-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:09.044-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:09.047-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:35:00+00:00, execution_date=20240725T123500, start_date=20240725T173008, end_date=20240725T173009
[2024-07-25T14:30:09.056-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2089 for task get_5m_info (too many values to unpack (expected 2); 2592981)
[2024-07-25T14:30:09.098-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:09.104-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:09.104-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:00:11.131-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:00:11.136-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [queued]>
[2024-07-25T15:00:11.139-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [queued]>
[2024-07-25T15:00:11.139-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:00:11.152-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:35:00+00:00
[2024-07-25T15:00:11.154-0300] {standard_task_runner.py:64} INFO - Started process 2619607 to run task
[2024-07-25T15:00:11.156-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:35:00+00:00', '--job-id', '2463', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpze3yjo0c']
[2024-07-25T15:00:11.156-0300] {standard_task_runner.py:91} INFO - Job 2463: Subtask get_5m_info
[2024-07-25T15:00:11.181-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:35:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:00:11.238-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:35:00+00:00'
[2024-07-25T15:00:11.239-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:00:11.305-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:00:11.306-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721922000&from=1721921700
[2024-07-25T15:00:11.626-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:00:11.627-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:00:11.630-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:35:00+00:00, execution_date=20240725T123500, start_date=20240725T180011, end_date=20240725T180011
[2024-07-25T15:00:11.656-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:00:11.662-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:00:11.662-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
