[2024-07-25T14:27:37.158-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:27:37.163-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T14:27:37.166-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T14:27:37.167-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:27:37.179-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:20:00+00:00
[2024-07-25T14:27:37.180-0300] {standard_task_runner.py:64} INFO - Started process 2590359 to run task
[2024-07-25T14:27:37.182-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:20:00+00:00', '--job-id', '2091', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp4h1666wk']
[2024-07-25T14:27:37.183-0300] {standard_task_runner.py:91} INFO - Job 2091: Subtask get_5m_info
[2024-07-25T14:27:37.210-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:27:37.254-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:20:00+00:00'
[2024-07-25T14:27:37.255-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:27:37.262-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:27:37.262-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:27:37.266-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:20:00+00:00, execution_date=20240725T122000, start_date=20240725T172737, end_date=20240725T172737
[2024-07-25T14:27:37.280-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2091 for task get_5m_info (too many values to unpack (expected 2); 2590359)
[2024-07-25T14:27:37.316-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:27:37.326-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:27:37.326-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:04.208-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:04.215-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T14:30:04.219-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T14:30:04.219-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:04.231-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:20:00+00:00
[2024-07-25T14:30:04.234-0300] {standard_task_runner.py:64} INFO - Started process 2592902 to run task
[2024-07-25T14:30:04.236-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:20:00+00:00', '--job-id', '2086', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpdqybs9pe']
[2024-07-25T14:30:04.237-0300] {standard_task_runner.py:91} INFO - Job 2086: Subtask get_5m_info
[2024-07-25T14:30:04.275-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:04.334-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:20:00+00:00'
[2024-07-25T14:30:04.334-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:04.341-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:04.341-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:04.345-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:20:00+00:00, execution_date=20240725T122000, start_date=20240725T173004, end_date=20240725T173004
[2024-07-25T14:30:04.355-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2086 for task get_5m_info (too many values to unpack (expected 2); 2592902)
[2024-07-25T14:30:04.369-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:04.375-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:04.376-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:49:30.814-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:49:30.820-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T14:49:30.824-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T14:49:30.825-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:49:30.838-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:20:00+00:00
[2024-07-25T14:49:30.840-0300] {standard_task_runner.py:64} INFO - Started process 2608895 to run task
[2024-07-25T14:49:30.842-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:20:00+00:00', '--job-id', '2162', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmppa6siztd']
[2024-07-25T14:49:30.843-0300] {standard_task_runner.py:91} INFO - Job 2162: Subtask get_5m_info
[2024-07-25T14:49:30.873-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:49:30.921-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:20:00+00:00'
[2024-07-25T14:49:30.922-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:49:30.994-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T14:49:30.995-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721921100&from=1721920800
[2024-07-25T14:49:31.275-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T14:49:31.276-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:49:31.279-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:20:00+00:00, execution_date=20240725T122000, start_date=20240725T174930, end_date=20240725T174931
[2024-07-25T14:49:31.301-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T14:49:31.308-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:49:31.309-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:00:00.338-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:00:00.345-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T15:00:00.349-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [queued]>
[2024-07-25T15:00:00.349-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:00:00.362-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:20:00+00:00
[2024-07-25T15:00:00.364-0300] {standard_task_runner.py:64} INFO - Started process 2619438 to run task
[2024-07-25T15:00:00.367-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:20:00+00:00', '--job-id', '2459', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpy_hs_2c6']
[2024-07-25T15:00:00.368-0300] {standard_task_runner.py:91} INFO - Job 2459: Subtask get_5m_info
[2024-07-25T15:00:00.398-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:20:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:00:00.453-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:20:00+00:00'
[2024-07-25T15:00:00.453-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:00:00.535-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:00:00.535-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721921100&from=1721920800
[2024-07-25T15:00:00.832-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:00:00.833-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:00:00.836-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:20:00+00:00, execution_date=20240725T122000, start_date=20240725T180000, end_date=20240725T180000
[2024-07-25T15:00:00.867-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:00:00.874-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:00:00.874-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
