[2024-07-25T12:30:02.205-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T12:30:02.209-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:25:00+00:00 [queued]>
[2024-07-25T12:30:02.213-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:25:00+00:00 [queued]>
[2024-07-25T12:30:02.213-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T12:30:02.227-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 15:25:00+00:00
[2024-07-25T12:30:02.228-0300] {standard_task_runner.py:64} INFO - Started process 2533417 to run task
[2024-07-25T12:30:02.230-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T15:25:00+00:00', '--job-id', '2059', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp2913oaof']
[2024-07-25T12:30:02.231-0300] {standard_task_runner.py:91} INFO - Job 2059: Subtask get_5m_info
[2024-07-25T12:30:02.256-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:25:00+00:00 [running]> on host Galaxybook.
[2024-07-25T12:30:02.303-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T15:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T15:25:00+00:00'
[2024-07-25T12:30:02.303-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T12:30:02.312-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T12:30:02.313-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 25, in execute
    to_time=to_timestamp(data_interval_end),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 15, in to_timestamp
    timestamp = int(datetime.timestamp(dt))
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object
[2024-07-25T12:30:02.385-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T15:25:00+00:00, execution_date=20240725T152500, start_date=20240725T153002, end_date=20240725T153002
[2024-07-25T12:30:02.396-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2059 for task get_5m_info (descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object; 2533417)
[2024-07-25T12:30:02.403-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T12:30:02.409-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T12:30:02.409-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:01:28.133-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:01:28.139-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:25:00+00:00 [queued]>
[2024-07-25T15:01:28.142-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:25:00+00:00 [queued]>
[2024-07-25T15:01:28.142-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:01:28.157-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 15:25:00+00:00
[2024-07-25T15:01:28.158-0300] {standard_task_runner.py:64} INFO - Started process 2620879 to run task
[2024-07-25T15:01:28.161-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T15:25:00+00:00', '--job-id', '2497', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpee0ne26z']
[2024-07-25T15:01:28.161-0300] {standard_task_runner.py:91} INFO - Job 2497: Subtask get_5m_info
[2024-07-25T15:01:28.185-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:25:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:01:28.240-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T15:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T15:25:00+00:00'
[2024-07-25T15:01:28.240-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:01:28.302-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:01:28.303-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721932200&from=1721931900
[2024-07-25T15:01:28.579-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:01:28.579-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:01:28.581-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T15:25:00+00:00, execution_date=20240725T152500, start_date=20240725T180128, end_date=20240725T180128
[2024-07-25T15:01:28.620-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:01:28.629-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:01:28.629-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
