[2024-07-25T10:17:02.706-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T10:17:02.711-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T13:16:00+00:00 [queued]>
[2024-07-25T10:17:02.714-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T13:16:00+00:00 [queued]>
[2024-07-25T10:17:02.714-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T10:17:02.725-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_1m_info> on 2024-07-25 13:16:00+00:00
[2024-07-25T10:17:02.727-0300] {standard_task_runner.py:64} INFO - Started process 2456469 to run task
[2024-07-25T10:17:02.729-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_1m', 'get_1m_info', 'scheduled__2024-07-25T13:16:00+00:00', '--job-id', '2054', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp285g3ncm']
[2024-07-25T10:17:02.730-0300] {standard_task_runner.py:91} INFO - Job 2054: Subtask get_1m_info
[2024-07-25T10:17:02.761-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T13:16:00+00:00 [running]> on host Galaxybook.
[2024-07-25T10:17:02.816-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_1m' AIRFLOW_CTX_TASK_ID='get_1m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T13:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T13:16:00+00:00'
[2024-07-25T10:17:02.816-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T10:17:02.878-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T10:17:02.878-0300] {mercado_hook.py:27} INFO - BASE URL: https://api.mercadobitcoin.net/api/v4
[2024-07-25T10:17:02.878-0300] {mercado_hook.py:33} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=1m&to=1721913422824&countback=1
[2024-07-25T10:17:03.176-0300] {logging_mixin.py:188} INFO - <Response [200]>
[2024-07-25T10:17:03.176-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T10:17:03.177-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 30, in execute
    json.dump(r.json, file)
  File "/usr/lib/python3.12/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
[2024-07-25T10:17:03.179-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_1m, task_id=get_1m_info, run_id=scheduled__2024-07-25T13:16:00+00:00, execution_date=20240725T131600, start_date=20240725T131702, end_date=20240725T131703
[2024-07-25T10:17:03.192-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2054 for task get_1m_info (Object of type method is not JSON serializable; 2456469)
[2024-07-25T10:17:03.228-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T10:17:03.234-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T10:17:03.235-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
