[2024-07-25T14:28:24.184-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:28:24.189-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [queued]>
[2024-07-25T14:28:24.192-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [queued]>
[2024-07-25T14:28:24.192-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:28:24.204-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 13:35:00+00:00
[2024-07-25T14:28:24.206-0300] {standard_task_runner.py:64} INFO - Started process 2591201 to run task
[2024-07-25T14:28:24.208-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T13:35:00+00:00', '--job-id', '2120', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmppyp6ftvv']
[2024-07-25T14:28:24.209-0300] {standard_task_runner.py:91} INFO - Job 2120: Subtask get_5m_info
[2024-07-25T14:28:24.234-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:28:24.276-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T13:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T13:35:00+00:00'
[2024-07-25T14:28:24.276-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:28:24.283-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:28:24.283-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:28:24.286-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T13:35:00+00:00, execution_date=20240725T133500, start_date=20240725T172824, end_date=20240725T172824
[2024-07-25T14:28:24.297-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2120 for task get_5m_info (too many values to unpack (expected 2); 2591201)
[2024-07-25T14:28:24.300-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:28:24.306-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:28:24.306-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:28.828-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:28.836-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [queued]>
[2024-07-25T14:30:28.839-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [queued]>
[2024-07-25T14:30:28.839-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:28.854-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 13:35:00+00:00
[2024-07-25T14:30:28.857-0300] {standard_task_runner.py:64} INFO - Started process 2593310 to run task
[2024-07-25T14:30:28.859-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T13:35:00+00:00', '--job-id', '2101', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpwtpt_xu_']
[2024-07-25T14:30:28.860-0300] {standard_task_runner.py:91} INFO - Job 2101: Subtask get_5m_info
[2024-07-25T14:30:28.900-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:28.953-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T13:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T13:35:00+00:00'
[2024-07-25T14:30:28.954-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:28.962-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:28.963-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:28.967-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T13:35:00+00:00, execution_date=20240725T133500, start_date=20240725T173028, end_date=20240725T173028
[2024-07-25T14:30:28.979-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2101 for task get_5m_info (too many values to unpack (expected 2); 2593310)
[2024-07-25T14:30:28.993-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:28.999-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:29.000-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:00:38.305-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:00:38.310-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [queued]>
[2024-07-25T15:00:38.313-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [queued]>
[2024-07-25T15:00:38.314-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:00:38.344-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 13:35:00+00:00
[2024-07-25T15:00:38.346-0300] {standard_task_runner.py:64} INFO - Started process 2620062 to run task
[2024-07-25T15:00:38.347-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T13:35:00+00:00', '--job-id', '2475', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmphopdz8ve']
[2024-07-25T15:00:38.348-0300] {standard_task_runner.py:91} INFO - Job 2475: Subtask get_5m_info
[2024-07-25T15:00:38.376-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T13:35:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:00:38.427-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T13:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T13:35:00+00:00'
[2024-07-25T15:00:38.428-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:00:38.492-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:00:38.492-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721925600&from=1721925300
[2024-07-25T15:00:38.855-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:00:38.856-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:00:38.859-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T13:35:00+00:00, execution_date=20240725T133500, start_date=20240725T180038, end_date=20240725T180038
[2024-07-25T15:00:38.892-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:00:38.900-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:00:38.900-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
