[2024-07-25T13:26:58.197-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T13:26:58.202-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T16:26:56.566475+00:00 [queued]>
[2024-07-25T13:26:58.205-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T16:26:56.566475+00:00 [queued]>
[2024-07-25T13:26:58.205-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T13:26:58.219-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 16:26:56.566475+00:00
[2024-07-25T13:26:58.221-0300] {standard_task_runner.py:64} INFO - Started process 2561475 to run task
[2024-07-25T13:26:58.223-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Binance_5m', 'get_5m_info', 'manual__2024-07-25T16:26:56.566475+00:00', '--job-id', '2094', '--raw', '--subdir', 'DAGS_FOLDER/binance_dag.py', '--cfg-path', '/tmp/tmp05jwg1zr']
[2024-07-25T13:26:58.224-0300] {standard_task_runner.py:91} INFO - Job 2094: Subtask get_5m_info
[2024-07-25T13:26:58.257-0300] {task_command.py:426} INFO - Running <TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T16:26:56.566475+00:00 [running]> on host Galaxybook.
[2024-07-25T13:26:58.317-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Binance_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T16:26:56.566475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T16:26:56.566475+00:00'
[2024-07-25T13:26:58.318-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T13:26:58.327-0300] {binance_dag.py:23} INFO - End Time: ../Datalake/bronze/mercado/binance_5m_2024-07-25.csv
[2024-07-25T13:26:58.382-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T13:26:58.382-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/binance_dag.py", line 32, in execute
    start_time=to_timestamp(start_time),
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/binance_dag.py", line 16, in to_timestamp
    return int(datetime.timestamp(dt))*1000
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object
[2024-07-25T13:26:58.385-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Binance_5m, task_id=get_5m_info, run_id=manual__2024-07-25T16:26:56.566475+00:00, execution_date=20240725T162656, start_date=20240725T162658, end_date=20240725T162658
[2024-07-25T13:26:58.394-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2094 for task get_5m_info (descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object; 2561475)
[2024-07-25T13:26:58.399-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T13:26:58.404-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T13:26:58.404-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
