[2024-07-25T16:05:11.970-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T16:05:11.976-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T19:05:10.285986+00:00 [queued]>
[2024-07-25T16:05:11.979-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T19:05:10.285986+00:00 [queued]>
[2024-07-25T16:05:11.979-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T16:05:12.005-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 19:05:10.285986+00:00
[2024-07-25T16:05:12.008-0300] {standard_task_runner.py:64} INFO - Started process 2651765 to run task
[2024-07-25T16:05:12.010-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Binance_5m', 'get_5m_info', 'manual__2024-07-25T19:05:10.285986+00:00', '--job-id', '2769', '--raw', '--subdir', 'DAGS_FOLDER/binance_dag.py', '--cfg-path', '/tmp/tmptcnt_cu6']
[2024-07-25T16:05:12.011-0300] {standard_task_runner.py:91} INFO - Job 2769: Subtask get_5m_info
[2024-07-25T16:05:12.048-0300] {task_command.py:426} INFO - Running <TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T19:05:10.285986+00:00 [running]> on host Galaxybook.
[2024-07-25T16:05:12.116-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Binance_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T19:05:10.285986+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T19:05:10.285986+00:00'
[2024-07-25T16:05:12.116-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T16:05:12.126-0300] {binance_dag.py:23} INFO - End Time: 2024-07-25 19:05:00+00:00
[2024-07-25T16:05:12.126-0300] {binance_dag.py:24} INFO - Start Time: 2024-07-25T19:00:00.00Z
[2024-07-25T16:05:12.207-0300] {binance_dag.py:25} INFO - Start timestamp: 1721944800000
[2024-07-25T16:05:12.207-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T16:05:12.207-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/binance_dag.py", line 26, in execute
    LOGGER.info(f"End timestamp: {to_timestamp(end_time)}")
                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/binance_dag.py", line 19, in to_timestamp
    dt = datetime.strptime(dt, "%Y-%m-%dT%H:%M:%S.%fZ")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-07-25 19:05:00+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
[2024-07-25T16:05:12.211-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Binance_5m, task_id=get_5m_info, run_id=manual__2024-07-25T19:05:10.285986+00:00, execution_date=20240725T190510, start_date=20240725T190511, end_date=20240725T190512
[2024-07-25T16:05:12.222-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2769 for task get_5m_info (time data '2024-07-25 19:05:00+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'; 2651765)
[2024-07-25T16:05:12.265-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T16:05:12.272-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T16:05:12.272-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
