[2024-07-25T14:29:04.841-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:29:04.846-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [queued]>
[2024-07-25T14:29:04.849-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [queued]>
[2024-07-25T14:29:04.849-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:29:04.861-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:40:00+00:00
[2024-07-25T14:29:04.862-0300] {standard_task_runner.py:64} INFO - Started process 2591889 to run task
[2024-07-25T14:29:04.865-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:40:00+00:00', '--job-id', '2146', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmppg9go7zk']
[2024-07-25T14:29:04.866-0300] {standard_task_runner.py:91} INFO - Job 2146: Subtask get_5m_info
[2024-07-25T14:29:04.898-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:29:04.951-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:40:00+00:00'
[2024-07-25T14:29:04.952-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:29:04.959-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:29:04.959-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:29:04.963-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:40:00+00:00, execution_date=20240725T144000, start_date=20240725T172904, end_date=20240725T172904
[2024-07-25T14:29:04.975-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2146 for task get_5m_info (too many values to unpack (expected 2); 2591889)
[2024-07-25T14:29:04.998-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:29:05.004-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:29:05.004-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:51.113-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:51.121-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [queued]>
[2024-07-25T14:30:51.125-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [queued]>
[2024-07-25T14:30:51.125-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:51.138-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:40:00+00:00
[2024-07-25T14:30:51.140-0300] {standard_task_runner.py:64} INFO - Started process 2593702 to run task
[2024-07-25T14:30:51.142-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:40:00+00:00', '--job-id', '2114', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpc9q4p9u5']
[2024-07-25T14:30:51.143-0300] {standard_task_runner.py:91} INFO - Job 2114: Subtask get_5m_info
[2024-07-25T14:30:51.175-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:51.235-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:40:00+00:00'
[2024-07-25T14:30:51.235-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:51.244-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:51.244-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 24, in execute
    to_time=to_timestamp(to_time),
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 15, in to_timestamp
    timestamp = int(datetime.timestamp(dt))
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object
[2024-07-25T14:30:51.248-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:40:00+00:00, execution_date=20240725T144000, start_date=20240725T173051, end_date=20240725T173051
[2024-07-25T14:30:51.324-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2114 for task get_5m_info (descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object; 2593702)
[2024-07-25T14:30:51.357-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:51.366-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:51.366-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:01:09.925-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:01:09.931-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [queued]>
[2024-07-25T15:01:09.934-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [queued]>
[2024-07-25T15:01:09.934-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:01:09.947-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:40:00+00:00
[2024-07-25T15:01:09.949-0300] {standard_task_runner.py:64} INFO - Started process 2620582 to run task
[2024-07-25T15:01:09.952-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:40:00+00:00', '--job-id', '2488', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpkors6izw']
[2024-07-25T15:01:09.953-0300] {standard_task_runner.py:91} INFO - Job 2488: Subtask get_5m_info
[2024-07-25T15:01:09.991-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:40:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:01:10.056-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:40:00+00:00'
[2024-07-25T15:01:10.056-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:01:10.130-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:01:10.131-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721929500&from=1721929200
[2024-07-25T15:01:10.417-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:01:10.418-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:01:10.420-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:40:00+00:00, execution_date=20240725T144000, start_date=20240725T180109, end_date=20240725T180110
[2024-07-25T15:01:10.450-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:01:10.456-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:01:10.457-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
