[2024-07-25T14:27:52.390-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:27:52.397-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [queued]>
[2024-07-25T14:27:52.400-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [queued]>
[2024-07-25T14:27:52.400-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:27:52.414-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:45:00+00:00
[2024-07-25T14:27:52.416-0300] {standard_task_runner.py:64} INFO - Started process 2590629 to run task
[2024-07-25T14:27:52.418-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:45:00+00:00', '--job-id', '2100', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmphamvje1u']
[2024-07-25T14:27:52.419-0300] {standard_task_runner.py:91} INFO - Job 2100: Subtask get_5m_info
[2024-07-25T14:27:52.451-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:27:52.505-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:45:00+00:00'
[2024-07-25T14:27:52.505-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:27:52.514-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:27:52.515-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:27:52.518-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:45:00+00:00, execution_date=20240725T124500, start_date=20240725T172752, end_date=20240725T172752
[2024-07-25T14:27:52.528-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2100 for task get_5m_info (too many values to unpack (expected 2); 2590629)
[2024-07-25T14:27:52.550-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:27:52.557-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:27:52.557-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:12.365-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:12.372-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [queued]>
[2024-07-25T14:30:12.375-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [queued]>
[2024-07-25T14:30:12.375-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:12.390-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:45:00+00:00
[2024-07-25T14:30:12.392-0300] {standard_task_runner.py:64} INFO - Started process 2593054 to run task
[2024-07-25T14:30:12.394-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:45:00+00:00', '--job-id', '2091', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp9hdyn_2v']
[2024-07-25T14:30:12.395-0300] {standard_task_runner.py:91} INFO - Job 2091: Subtask get_5m_info
[2024-07-25T14:30:12.423-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:12.470-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:45:00+00:00'
[2024-07-25T14:30:12.470-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:12.477-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:12.477-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:12.482-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:45:00+00:00, execution_date=20240725T124500, start_date=20240725T173012, end_date=20240725T173012
[2024-07-25T14:30:12.492-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2091 for task get_5m_info (too many values to unpack (expected 2); 2593054)
[2024-07-25T14:30:12.527-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:12.534-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:12.534-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:00:14.644-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:00:14.652-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [queued]>
[2024-07-25T15:00:14.656-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [queued]>
[2024-07-25T15:00:14.657-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:00:14.679-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 12:45:00+00:00
[2024-07-25T15:00:14.681-0300] {standard_task_runner.py:64} INFO - Started process 2619655 to run task
[2024-07-25T15:00:14.683-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T12:45:00+00:00', '--job-id', '2465', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpcfsh6hyw']
[2024-07-25T15:00:14.684-0300] {standard_task_runner.py:91} INFO - Job 2465: Subtask get_5m_info
[2024-07-25T15:00:14.716-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T12:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:00:14.781-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T12:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T12:45:00+00:00'
[2024-07-25T15:00:14.781-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:00:14.864-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:00:14.865-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721922600&from=1721922300
[2024-07-25T15:00:15.183-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:00:15.184-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:00:15.187-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T12:45:00+00:00, execution_date=20240725T124500, start_date=20240725T180014, end_date=20240725T180015
[2024-07-25T15:00:15.221-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:00:15.228-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:00:15.228-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
