[2024-07-25T14:29:07.592-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:29:07.597-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [queued]>
[2024-07-25T14:29:07.600-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [queued]>
[2024-07-25T14:29:07.600-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:29:07.613-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:45:00+00:00
[2024-07-25T14:29:07.615-0300] {standard_task_runner.py:64} INFO - Started process 2591927 to run task
[2024-07-25T14:29:07.617-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:45:00+00:00', '--job-id', '2148', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpixu9a736']
[2024-07-25T14:29:07.618-0300] {standard_task_runner.py:91} INFO - Job 2148: Subtask get_5m_info
[2024-07-25T14:29:07.645-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:29:07.697-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:45:00+00:00'
[2024-07-25T14:29:07.697-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:29:07.704-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:29:07.704-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:29:07.707-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:45:00+00:00, execution_date=20240725T144500, start_date=20240725T172907, end_date=20240725T172907
[2024-07-25T14:29:07.718-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2148 for task get_5m_info (too many values to unpack (expected 2); 2591927)
[2024-07-25T14:29:07.750-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:29:07.756-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:29:07.756-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:53.546-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:53.552-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [queued]>
[2024-07-25T14:30:53.556-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [queued]>
[2024-07-25T14:30:53.556-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:53.568-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:45:00+00:00
[2024-07-25T14:30:53.570-0300] {standard_task_runner.py:64} INFO - Started process 2593719 to run task
[2024-07-25T14:30:53.571-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:45:00+00:00', '--job-id', '2115', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpgodciqk9']
[2024-07-25T14:30:53.572-0300] {standard_task_runner.py:91} INFO - Job 2115: Subtask get_5m_info
[2024-07-25T14:30:53.600-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:53.649-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:45:00+00:00'
[2024-07-25T14:30:53.650-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:53.657-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:53.657-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 24, in execute
    to_time=to_timestamp(to_time),
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 15, in to_timestamp
    timestamp = int(datetime.timestamp(dt))
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object
[2024-07-25T14:30:53.661-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:45:00+00:00, execution_date=20240725T144500, start_date=20240725T173053, end_date=20240725T173053
[2024-07-25T14:30:53.721-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2115 for task get_5m_info (descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object; 2593719)
[2024-07-25T14:30:53.746-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:53.753-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:53.754-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:01:11.641-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:01:11.650-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [queued]>
[2024-07-25T15:01:11.655-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [queued]>
[2024-07-25T15:01:11.655-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:01:11.670-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:45:00+00:00
[2024-07-25T15:01:11.673-0300] {standard_task_runner.py:64} INFO - Started process 2620624 to run task
[2024-07-25T15:01:11.675-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:45:00+00:00', '--job-id', '2489', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpl7ayx3ry']
[2024-07-25T15:01:11.676-0300] {standard_task_runner.py:91} INFO - Job 2489: Subtask get_5m_info
[2024-07-25T15:01:11.708-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:01:11.760-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:45:00+00:00'
[2024-07-25T15:01:11.761-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:01:11.828-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:01:11.828-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721929800&from=1721929500
[2024-07-25T15:01:12.138-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:01:12.139-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:01:12.141-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:45:00+00:00, execution_date=20240725T144500, start_date=20240725T180111, end_date=20240725T180112
[2024-07-25T15:01:12.173-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:01:12.179-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:01:12.180-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
