[2024-07-25T14:28:58.181-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:28:58.187-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [queued]>
[2024-07-25T14:28:58.191-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [queued]>
[2024-07-25T14:28:58.191-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:28:58.208-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:30:00+00:00
[2024-07-25T14:28:58.211-0300] {standard_task_runner.py:64} INFO - Started process 2591783 to run task
[2024-07-25T14:28:58.213-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:30:00+00:00', '--job-id', '2142', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmplcm3j_9g']
[2024-07-25T14:28:58.215-0300] {standard_task_runner.py:91} INFO - Job 2142: Subtask get_5m_info
[2024-07-25T14:28:58.245-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:28:58.297-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:30:00+00:00'
[2024-07-25T14:28:58.297-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:28:58.307-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:28:58.307-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:28:58.312-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:30:00+00:00, execution_date=20240725T143000, start_date=20240725T172858, end_date=20240725T172858
[2024-07-25T14:28:58.324-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2142 for task get_5m_info (too many values to unpack (expected 2); 2591783)
[2024-07-25T14:28:58.346-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:28:58.354-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:28:58.354-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T14:30:48.863-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:48.869-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [queued]>
[2024-07-25T14:30:48.872-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [queued]>
[2024-07-25T14:30:48.872-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:48.885-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:30:00+00:00
[2024-07-25T14:30:48.887-0300] {standard_task_runner.py:64} INFO - Started process 2593633 to run task
[2024-07-25T14:30:48.889-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:30:00+00:00', '--job-id', '2112', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp_59p_caq']
[2024-07-25T14:30:48.889-0300] {standard_task_runner.py:91} INFO - Job 2112: Subtask get_5m_info
[2024-07-25T14:30:48.915-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:48.964-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:30:00+00:00'
[2024-07-25T14:30:48.965-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:48.971-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:48.971-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:48.975-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:30:00+00:00, execution_date=20240725T143000, start_date=20240725T173048, end_date=20240725T173048
[2024-07-25T14:30:48.986-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2112 for task get_5m_info (too many values to unpack (expected 2); 2593633)
[2024-07-25T14:30:49.022-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:49.028-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:49.028-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:01:05.357-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:01:05.363-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [queued]>
[2024-07-25T15:01:05.366-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [queued]>
[2024-07-25T15:01:05.366-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:01:05.382-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:30:00+00:00
[2024-07-25T15:01:05.384-0300] {standard_task_runner.py:64} INFO - Started process 2620538 to run task
[2024-07-25T15:01:05.386-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:30:00+00:00', '--job-id', '2486', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmp866pl9nn']
[2024-07-25T15:01:05.387-0300] {standard_task_runner.py:91} INFO - Job 2486: Subtask get_5m_info
[2024-07-25T15:01:05.419-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:30:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:01:05.480-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:30:00+00:00'
[2024-07-25T15:01:05.480-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:01:05.549-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:01:05.550-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721928900&from=1721928600
[2024-07-25T15:01:05.850-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:01:05.850-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:01:05.853-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:30:00+00:00, execution_date=20240725T143000, start_date=20240725T180105, end_date=20240725T180105
[2024-07-25T15:01:05.883-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:01:05.889-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:01:05.890-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
