[2024-07-25T12:50:02.227-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T12:50:02.235-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:45:00+00:00 [queued]>
[2024-07-25T12:50:02.238-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:45:00+00:00 [queued]>
[2024-07-25T12:50:02.238-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T12:50:02.256-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 15:45:00+00:00
[2024-07-25T12:50:02.258-0300] {standard_task_runner.py:64} INFO - Started process 2542918 to run task
[2024-07-25T12:50:02.261-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T15:45:00+00:00', '--job-id', '2069', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpkxu3eb8m']
[2024-07-25T12:50:02.262-0300] {standard_task_runner.py:91} INFO - Job 2069: Subtask get_5m_info
[2024-07-25T12:50:02.297-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T12:50:02.356-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T15:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T15:45:00+00:00'
[2024-07-25T12:50:02.357-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T12:50:02.366-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T12:50:02.367-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 25, in execute
    to_time=to_timestamp(data_interval_end),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 15, in to_timestamp
    timestamp = int(datetime.timestamp(dt))
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object
[2024-07-25T12:50:02.454-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T15:45:00+00:00, execution_date=20240725T154500, start_date=20240725T155002, end_date=20240725T155002
[2024-07-25T12:50:02.466-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2069 for task get_5m_info (descriptor 'timestamp' for 'datetime.datetime' objects doesn't apply to a 'str' object; 2542918)
[2024-07-25T12:50:02.478-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T12:50:02.484-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T12:50:02.485-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:01:37.780-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:01:37.786-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:45:00+00:00 [queued]>
[2024-07-25T15:01:37.790-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:45:00+00:00 [queued]>
[2024-07-25T15:01:37.790-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:01:37.804-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 15:45:00+00:00
[2024-07-25T15:01:37.806-0300] {standard_task_runner.py:64} INFO - Started process 2621055 to run task
[2024-07-25T15:01:37.808-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T15:45:00+00:00', '--job-id', '2501', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpgvl701xz']
[2024-07-25T15:01:37.809-0300] {standard_task_runner.py:91} INFO - Job 2501: Subtask get_5m_info
[2024-07-25T15:01:37.839-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T15:45:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:01:37.923-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T15:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T15:45:00+00:00'
[2024-07-25T15:01:37.923-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:01:38.003-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:01:38.003-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721933400&from=1721933100
[2024-07-25T15:01:38.293-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:01:38.294-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:01:38.297-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T15:45:00+00:00, execution_date=20240725T154500, start_date=20240725T180137, end_date=20240725T180138
[2024-07-25T15:01:38.346-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:01:38.354-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:01:38.355-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
