[2024-07-24T23:51:09.548-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T23:51:09.554-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T02:09:00+00:00 [queued]>
[2024-07-24T23:51:09.557-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T02:09:00+00:00 [queued]>
[2024-07-24T23:51:09.557-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T23:51:09.573-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_1m_info> on 2024-07-25 02:09:00+00:00
[2024-07-24T23:51:09.575-0300] {standard_task_runner.py:64} INFO - Started process 2283010 to run task
[2024-07-24T23:51:09.577-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_1m', 'get_1m_info', 'scheduled__2024-07-25T02:09:00+00:00', '--job-id', '1733', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmpuuloezih']
[2024-07-24T23:51:09.578-0300] {standard_task_runner.py:91} INFO - Job 1733: Subtask get_1m_info
[2024-07-24T23:51:09.611-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_1m.get_1m_info scheduled__2024-07-25T02:09:00+00:00 [running]> on host Galaxybook.
[2024-07-24T23:51:09.659-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_1m' AIRFLOW_CTX_TASK_ID='get_1m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T02:09:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T02:09:00+00:00'
[2024-07-24T23:51:09.659-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T23:51:09.666-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T23:51:09.666-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/mercado_dag.py", line 22, in execute
    with open('../../Datalake/mercado/mercado_1m.csv', 'a', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../Datalake/mercado/mercado_1m.csv'
[2024-07-24T23:51:09.670-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_1m, task_id=get_1m_info, run_id=scheduled__2024-07-25T02:09:00+00:00, execution_date=20240725T020900, start_date=20240725T025109, end_date=20240725T025109
[2024-07-24T23:51:09.680-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 1733 for task get_1m_info ([Errno 2] No such file or directory: '../../Datalake/mercado/mercado_1m.csv'; 2283010)
[2024-07-24T23:51:09.710-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T23:51:09.718-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T23:51:09.718-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
